# Exercise 2.A Fundamentals of pandas

In [2]:
import numpy as np
import pandas as pd

## Series

In [3]:
aa = [1, 2, 3, 4]
ab = (5, 6, 7, 8)
ac = {9, 10, 11, 12}
ad = {
    'first': 13,
    'second': 14,
    'third': 15,
    'fourth': 16
}

In [4]:
ser1 = pd.Series(aa)
print(ser1)

0    1
1    2
2    3
3    4
dtype: int64

In [5]:
ser2 = pd.Series(ab)
print(ser2)

0    5
1    6
2    7
3    8
dtype: int64

In [6]:
ser3 = pd.Series(list(ac)) #Switched to list to run properly
print(ser3) # Set types are incompatible with pd.series() b/c it's unordered

0     9
1    10
2    11
3    12
dtype: int64

In [7]:
ser4 = pd.Series(ad)
print(ser4)

first     13
second    14
third     15
fourth    16
dtype: int64

In [8]:
ser5 = pd.Series(17, 18, 19, 20)
print(ser5) #TypeError: Index(...) must be called with a collection of some kind, 18 was passed

TypeError: Index(...) must be called with a collection of some kind, 18 was passed

## DataFrames from Series

In [11]:
df1 = pd.DataFrame(ser1)

In [12]:
df1

   0
0  1
1  2
2  3
3  4

In [19]:
df1.insert(1,1,ser2)
df1

ValueError: cannot insert 1, already exists

In [18]:
df1.insert(1, 2, ser3)
df1

ValueError: cannot insert 2, already exists

In [14]:
df1.insert(1, 4, ser4) #This displays all values as NaN which makes it hard to accurately read the data
df1

   0   4   3
0  1 NaN   9
1  2 NaN  10
2  3 NaN  11
3  4 NaN  12

In [20]:
df1

   0  1   2   4   3
0  1  5   9 NaN   9
1  2  6  10 NaN  10
2  3  7  11 NaN  11
3  4  8  12 NaN  12

In [22]:
df1.loc[4] = [5, 9, 12, 0, 0]
df1

   0  1   2    4   3
0  1  5   9  NaN   9
1  2  6  10  NaN  10
2  3  7  11  NaN  11
3  4  8  12  NaN  12
4  5  9  12  0.0   0

## Reading Data into a DataFrame

In [24]:
df2 = pd.read_csv('sakila_example.csv')
df2

,title,description,category,language,actor_name
0,ACADEMY DINOSAUR,A Epic Drama of a Feminist And a Mad Scientist...,Documentary,English,PENELOPE GUINESS
1,ACADEMY DINOSAUR,A Epic Drama of a Feminist And a Mad Scientist...,Documentary,English,CHRISTIAN GABLE
2,ACADEMY DINOSAUR,A Epic Drama of a Feminist And a Mad Scientist...,Documentary,English,LUCILLE TRACY
3,ACADEMY DINOSAUR,A Epic Drama of a Feminist And a Mad Scientist...,Documentary,English,SANDRA PECK
4,ACADEMY DINOSAUR,A Epic Drama of a Feminist And a Mad Scientist...,Documentary,English,JOHNNY CAGE
...,...,...,...,...,...
257,ATTRACTION NEWTON,A Astounding Panorama of a Composer And a Fris...,New,English,GARY PENN
258,ATTRACTION NEWTON,A Astounding Panorama of a Composer And a Fris...,New,English,CHRISTOPHER WEST
259,AUTUMN CROW,A Beautiful Tale of a Dentist And a Mad Cow wh...,Games,English,DUSTIN TAUTOU
260,AUTUMN CROW,A Beautiful Tale of a Dentist And a Mad Cow wh...,Games,English,ANGELA HUDSON
261,AUTUMN CROW,A Beautiful Tale of a Dentist And a Mad Cow wh...,Games,English,JAMES PITT

In [26]:
df2.head() # Shows Header and top 5

,title,description,category,language,actor_name
0,ACADEMY DINOSAUR,A Epic Drama of a Feminist And a Mad Scientist...,Documentary,English,PENELOPE GUINESS
1,ACADEMY DINOSAUR,A Epic Drama of a Feminist And a Mad Scientist...,Documentary,English,CHRISTIAN GABLE
2,ACADEMY DINOSAUR,A Epic Drama of a Feminist And a Mad Scientist...,Documentary,English,LUCILLE TRACY
3,ACADEMY DINOSAUR,A Epic Drama of a Feminist And a Mad Scientist...,Documentary,English,SANDRA PECK
4,ACADEMY DINOSAUR,A Epic Drama of a Feminist And a Mad Scientist...,Documentary,English,JOHNNY CAGE

In [30]:
df2.tail(10) # Shows the last x and the Header

,title,description,category,language,actor_name
252,ATTACKS HATE,A Fast-Paced Panorama of a Technical Writer An...,Sci-Fi,English,MILLA KEITEL
253,ATTACKS HATE,A Fast-Paced Panorama of a Technical Writer An...,Sci-Fi,English,GROUCHO DUNST
254,ATTACKS HATE,A Fast-Paced Panorama of a Technical Writer An...,Sci-Fi,English,BURT TEMPLE
255,ATTRACTION NEWTON,A Astounding Panorama of a Composer And a Fris...,New,English,UMA WOOD
256,ATTRACTION NEWTON,A Astounding Panorama of a Composer And a Fris...,New,English,RIP WINSLET
257,ATTRACTION NEWTON,A Astounding Panorama of a Composer And a Fris...,New,English,GARY PENN
258,ATTRACTION NEWTON,A Astounding Panorama of a Composer And a Fris...,New,English,CHRISTOPHER WEST
259,AUTUMN CROW,A Beautiful Tale of a Dentist And a Mad Cow wh...,Games,English,DUSTIN TAUTOU
260,AUTUMN CROW,A Beautiful Tale of a Dentist And a Mad Cow wh...,Games,English,ANGELA HUDSON
261,AUTUMN CROW,A Beautiful Tale of a Dentist And a Mad Cow wh...,Games,English,JAMES PITT

In [32]:
df2.describe() # Displays the count, unique, top, most freq

,title,description,category,language,actor_name
count,262,262,262,262,262
unique,46,46,15,1,145
top,ARABIA DOGMA,A Touching Epistle of a Madman And a Mad Cow w...,Horror,English,OPRAH KILMER
freq,12,12,55,262,8

After using the describe function to better understand the data, I can now clearly see that Arabia Dogma is the top performing movie

In [33]:
df3 = pd.read_csv('northwind_example.csv')
df3

     OrderID                    ProductName  UnitPrice  Quantity
0      10248                 Queso Cabrales       14.0        12
1      10248  Singaporean Hokkien Fried Mee        9.8        10
2      10248         Mozzarella di Giovanni       34.8         5
3      10249          Manjimup Dried Apples       42.4        40
4      10249                           Tofu       18.6         9
..       ...                            ...        ...       ...
495    10435         Mozzarella di Giovanni       27.8        10
496    10436         Gnocchi di nonna Alice       30.4        40
497    10436       Wimmers gute Semmelkndel       26.6        30
498    10436             Rhnbru Klosterbier        6.2        24
499    10436                      Spegesild        9.6         5

[500 rows x 4 columns]

In [34]:
df3.describe()

            OrderID   UnitPrice    Quantity
count    500.000000  500.000000  500.000000
mean   10341.364000   23.371400   24.330000
std       54.442663   27.334436   18.069702
min    10248.000000    2.000000    1.000000
25%    10294.000000   10.400000   10.000000
50%    10341.000000   15.800000   20.000000
75%    10389.000000   27.800000   32.000000
max    10436.000000  210.800000  120.000000

From looking at the description of the csv files I was able to observe that the average price of items were about $23 with their highest being $210 and lowest being $2. This dataset gave me a more descriptive breakdown of the csv file including the STDV and the mean of said data unlike DF1.

## Coding a DataFrame

In [35]:
test_data = {
    'ID': [1, 2, 3, 4, 5, 6, 7, 8],
    'Name': ['Alicia', 'Bob', 'Charlie', 'Dominic', 'Eve', 'Frank', 'Grace', 'Heidi'],
    'Age': [25, np.nan, 22, 19, 31, 35, np.nan, 18],
    'City': ['NY', 'LA', 'Chicago', 'Houston', 'Phoenix', 'Boston', 'Austin', 'San Diego'],
    'Score': [85, 92, -1, 65, 78, np.nan, 55, 90]
}

df4 = pd.Series(test_data)

df4

ID                                [1, 2, 3, 4, 5, 6, 7, 8]
Name     [Alicia, Bob, Charlie, Dominic, Eve, Frank, Gr...
Age                     [25, nan, 22, 19, 31, 35, nan, 18]
City     [NY, LA, Chicago, Houston, Phoenix, Boston, Au...
Score                    [85, 92, -1, 65, 78, nan, 55, 90]
dtype: object

In [ ]:
df4.to_csv('df4_csv', index = False)